version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - backend_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: always
    networks:
      - backend_network
      
networks:
  backend_network:
    external: true

